name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
      - release-*

jobs:
  hello:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: hello
        run: |
          mkdir screenshots
          echo  "hello" > screenshots/hello.txt
      - name: Save PR number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo ${{ github.event.number }} > ./screenshots/PR
      - name: save screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-macos
          path: screenshots
