name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
      - release-*

jobs:
  hello:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: hello
        run: echo  "hello"
