name: Echo

on:
  workflow_call:
    inputs:
      commit:
        required: true
        type: string
      branch:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
      
      - name: Echo
        run: |
          echo "Commit: ${{ inputs.commit }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "OS: ${{ inputs.os }}"
